version: "3.8"

services:
  mongo-backend:
    image: mongo
    restart: always
    container_name: mongo-backend
    ports:
      - "27057:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_network

volumes:
  mongo-data:

networks:
  mongo_network:
    driver: bridge
